#!/bin/bash

basedir=$(dirname $0)

sudo apt update
sudo apt install php-cli php-pgsql php-json sqlite3 python3 python3-pip python3-venv
sudo apt install postgresql
sudo apt install openjdk-17-jdk
sudo apt install unzip
sudo apt install libswt-gtk-4-java

cd $basedir

mkdir bin

# install https://github.com/maaslalani/slides/releases
read -p "APakah akan menghapus dan menginstall ulang slides ? (ketik ya jika ingin melakukan) " keputusan

if [ "$keputusan" = "ya" ]
then

	cd bin
	mkdir slides
	cd slides
	wget https://github.com/maaslalani/slides/releases/download/v0.9.0/slides_0.9.0_linux_amd64.tar.gz
	tar xvf slides_0.9.0_linux_amd64.tar.gz
	rm slides_0.9.0_linux_amd64.tar.gz

fi

cd $basedir

# install  apache hop
read -p "Apakah Akan menghapus dan Menginstall Ulang Apache Hop ? (ketik ya jika ingin melakukan) " keputusan

if [ "$keputusan" = "ya" ]
then
	cd bin
	rm -rf hop
	wget https://dlcdn.apache.org/hop/2.14.0/apache-hop-client-2.14.0.zip
	unzip apache-hop-client-2.14.0.zip
	rm apache-hop-client-2.14.0.zip
fi

cd $basedir

# install  dbbeaver 
read -p "Apakah akan menghapus dan menginstall ulang dbbeaver ? (ketik ya jika ingin melakukan) " keputusan

if [ "$keputusan" = "ya" ]
then

	cd ~/bin
	rm -rf dbbeaver
	wget https://dbeaver.io/files/dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
	tar xvf dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
	rm dbeaver-ce-latest-linux.gtk.x86_64.tar.gz

fi
