#!/bin/bash

basedir=$(dirname $0)

sudo apt update
sudo apt install postgresql
sudo apt install openjdk-21-jdk-headless
sudo apt install bzip2
sudo apt install python3 python3-venv python3-pip

cd $basedir

mkdir bin

cd $basedir

# install  apache hop
read -p "Apakah Akan menghapus dan Menginstall Ulang Apache Nifi ? (ketik ya jika ingin melakukan) " keputusan

if [ "$keputusan" = "ya" ]
then
	cd bin
	rm -rf nifi
	wget https://dlcdn.apache.org/nifi/2.4.0/nifi-2.4.0-bin.zip
	unzip nifi-2.4.0-bin.zip
	rm nifi-2.4.0.zip
fi


sudo systemctl disable postgresql
