#!/bin/bash

basedir=$(dirname $0)

sudo apt update
sudo apt install postgresql openjdk-17-jdk bzip2 unzip php-cli php-pgsql php-sqlite3 libswt-gtk-4-java sqlite3 php-dev build-essential composer
sudo pecl install msgpack
sudo pecl install protobuf

echo "extension=msgpack.so" | sudo tee /etc/php/8.3/mods-available/msgpack.ini
echo "extension=msgpack.so" | sudo tee /etc/php/8.3/cli/conf.d/20-msgpack.ini

echo "extension=protobuf.so" | sudo tee /etc/php/8.3/mods-available/protobuf.ini
echo "extension=protobuf.so" | sudo tee /etc/php/8.3/cli/conf.d/20-protobuf.ini

cd $basedir
mkdir bin
cd $basedir/bin

# install protoc protobuffer compiler

mkdir protoc
cd protoc

wget https://github.com/protocolbuffers/protobuf/releases/download/v31.1/protoc-31.1-linux-x86_64.zip
unzip protoc-31.1-linux-x86_64.zip
rm protoc-31.1-linux-x86_64.zip

cd ..

# install apache hop
read -p "Apakah Akan menghapus dan Menginstall Ulang Apache Hop ? (ketik ya jika ingin melakukan) " keputusan

if [ "$keputusan" = "ya" ]
then
	rm -rf hop
	wget https://dlcdn.apache.org/hop/2.14.0/apache-hop-client-2.14.0.zip
	unzip apache-hop-client-2.14.0.zip
	rm apache-hop-client-2.14.0.zip
fi

keputusan="tidak"

# install dbbeaver
read -p "Apakah Akan Menghapus dan Menginstall Ulang dbbeaver ? (ketik ya jika ingin melakukan) " keputusan

if [ "$keputusan" = "ya" ]
then
	rm -rf dbbeaver
	wget https://dbeaver.io/files/dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
	tar xvf dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
	rm dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
fi
