#!/bin/bash

current_dir=$(dirname $0)

cd $current_dir

read -p "APakah akan menghapus dan menginstall ulang database stackoverflow ? (ketik ya jika ingin melakukan) " keputusan

if [ "$keputusan" = "ya" ]
then

	sudo -u postgres psql -c "DROP DATABASE stackoverflow;"
	sudo -u postgres psql -c "CREATE DATABASE stackoverflow;"
	sudo -u postgres psql -d stackoverflow < stackoverflow-ddl.sql

	dir=$(mktemp -d)

	chmod -R 777 $dir

	cp *.sql $dir

	cd $dir

	# users
	wget https://ia800508.us.archive.org/30/items/stackexchange/stackoverflow.com-Users.7z

	7z e "stackoverflow.com-Users.7z"
	rm "stackoverflow.com-Users.7z"

	sudo -u postgres psql -d stackoverflow < stackoverflow-load-users.sql

	rm *.xml

	#badges
	wget https://ia800508.us.archive.org/30/items/stackexchange/stackoverflow.com-Badges.7z

	7z e "stackoverflow.com-Badges.7z"
	rm "stackoverflow.com-Badges.7z"

	sudo -u postgres psql -d stackoverflow < stackoverflow-load-badges.sql

	rm *.xml

	#comments

	wget https://ia800508.us.archive.org/30/items/stackexchange/stackoverflow.com-Comments.7z

	7z e "stackoverflow.com-Comments.7z"
	rm "stackoverflow.com-Comments.7z"

	sudo -u postgres psql -d stackoverflow < stackoverflow-load-comments.sql

	rm *.xml

	#Post History

	wget https://ia800508.us.archive.org/30/items/stackexchange/stackoverflow.com-PostHistory.7z

	7z e "stackoverflow.com-PostHistory.7z"
	rm "stackoverflow.com-PostHistory.7z"

	sudo -u postgres psql -d stackoverflow < stackoverflow-load-posthistory.sql

	rm *.xml

	#post links

	wget https://ia800508.us.archive.org/30/items/stackexchange/stackoverflow.com-PostLinks.7z

	7z e "stackoverflow.com-PostLinks.7z"
	rm "stackoverflow.com-PostLinks.7z"

	sudo -u postgres psql -d stackoverflow < stackoverflow-load-postlinks.sql

	rm *.xml


	#Posts

	wget https://ia800508.us.archive.org/30/items/stackexchange/stackoverflow.com-Posts.7z

	7z e "stackoverflow.com-Posts.7z"
	rm "stackoverflow.com-Posts.7z"


	sudo -u postgres psql -d stackoverflow < stackoverflow-load-posts.sql

	rm *.xml


	#tags

	wget https://ia800508.us.archive.org/30/items/stackexchange/stackoverflow.com-Tags.7z

	7z e "stackoverflow.com-Tags.7z"
	rm "stackoverflow.com-Tags.7z"

	sudo -u postgres psql -d stackoverflow < stackoverflow-load-tags.sql

	rm *.xml


	#votes

	wget https://ia800508.us.archive.org/30/items/stackexchange/stackoverflow.com-Votes.7z

	7z e "stackoverflow.com-Votes.7z"
	rm "stackoverflow.com-Votes.7z"

	sudo -u postgres psql -d stackoverflow < stackoverflow-load-votes.sql

	rm *.xml

	sudo -u postgres psql -d stackoverflow -c "DROP TABLE data_load;"

	cd $current_dir

	rm -rf $dir

fi
